services:
  postgres:
    image: postgres:16-alpine
    container_name: contajunto_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: contajunto
      POSTGRES_PASSWORD: contajunto123
      POSTGRES_DB: contajunto_dev
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
